/**
 * Detalle profundo del episodio de la semana 12, que alimenta las seis
 * pestañas del Centro de Contenido. Solo este episodio lo trae, para que se
 * vea cómo luce una semana completamente trabajada; el resto arrancan sin
 * detalle y muestran los bloques listos para llenarse.
 */

import type { EpisodeDetail } from "@/lib/content-types";

export const DEMO_EPISODE_DETAIL: EpisodeDetail = {
  description:
    "Muchas familias creen que los Trusts son solo para personas ricas. En este episodio desmitificamos los Trusts y explicamos cuándo, por qué y cómo pueden proteger a tu familia, aunque no seas millonario.",
  dates: "22 – 28 mar 2027",
  episodeLabel: "Ep. 12",
  guest: {
    name: "Sonia Muñoz Gallagher",
    role: "Abogada de Estate Planning",
    org: "Socia en Gallagher Law Group",
    location: "Miami, FL",
    email: "sonia@gallagherlawgroup.com",
    phone: "(305) 555-0123",
    website: "GallagherLawGroup.com",
    actionLabel: "Ver ficha completa",
  },
  keyPoints: [
    "Los Trusts no son solo para millonarios.",
    "Protección de la familia y de los menores.",
    "Evitar el probate y ahorrar tiempo y dinero.",
    "Flexibilidad y control de tus bienes.",
    "Pasos prácticos para crear tu primer Trust.",
  ],
  generalInfo: [
    { label: "Estado", value: "En Producción", tone: "amber" },
    { label: "Tipo de episodio", value: "Educativo" },
    { label: "Duración estimada", value: "45 – 60 min" },
    { label: "Grabación", value: "15 mar 2027" },
    { label: "Publicación podcast", value: "22 mar 2027" },
    { label: "Responsable", value: "Diana Bermeo", person: true },
    { label: "Productor", value: "Anthony Aguilar", person: true },
    { label: "Prioridad", value: "Alta", icon: "Flag" },
  ],
  productionInfo: [
    { label: "Estado", value: "En Producción", tone: "amber" },
    { label: "Etapa actual", value: "Edición" },
    { label: "Fecha de grabación", value: "15 mar 2027" },
    { label: "Duración estimada", value: "45 – 60 min" },
    { label: "Productor", value: "Anthony Aguilar", person: true },
    { label: "Editor", value: "Carla Rodríguez", person: true },
    { label: "Diseñador", value: "Luis Hernández", person: true },
    { label: "Prioridad", value: "Alta", icon: "Flag" },
  ],
  distributionFlow: [
    { id: "podcast", label: "Podcast", sub: "Episodio madre", icon: "Mic", color: "#a78bfa", status: "En Producción" },
    { id: "youtube", label: "YouTube", sub: "Video largo", icon: "Video", color: "#ef4444", status: "En Producción" },
    { id: "reels", label: "Reels", sub: "10 videos", icon: "Camera", color: "#f472b6", status: "En Producción" },
    { id: "shorts", label: "Shorts", sub: "5 videos", icon: "Music2", color: "#3b82f6", status: "Pendiente" },
    { id: "carrusel", label: "Carrusel", sub: "Instagram", icon: "Rows3", color: "#22c55e", status: "En Producción" },
    { id: "articulo", label: "Artículo", sub: "Blog / SEO", icon: "FileText", color: "#e0a836", status: "En Producción" },
    { id: "pdf", label: "PDF / Guía", sub: "Descargable", icon: "FileDown", color: "#a78bfa", status: "Pendiente" },
    { id: "email", label: "Email", sub: "Secuencia", icon: "Mail", color: "#22c55e", status: "Pendiente" },
    { id: "academia", label: "Academia", sub: "Clase", icon: "GraduationCap", color: "#3b82f6", status: "No Iniciado" },
  ],
  assets: [
    { id: "a1", index: 1, title: "Podcast (Madre)", icon: "Mic", color: "#a78bfa", progress: 100, lines: [{ label: "Grabación", done: true }, { label: "Edición de audio", done: true }, { label: "Mastering", done: true }, { label: "Publicación", done: true }], footerNote: "Publicado: 16 mar 2027", footerAction: "Ver activo" },
    { id: "a2", index: 2, title: "YouTube (Largo)", icon: "Video", color: "#ef4444", progress: 100, lines: [{ label: "Edición de video", done: true }, { label: "Miniatura", done: true }, { label: "Descripción & SEO", done: true }, { label: "Publicado en YouTube", done: true }], footerNote: "Publicado: 17 mar 2027", footerAction: "Ver en YouTube" },
    { id: "a3", index: 3, title: "Clips & Shorts", icon: "Scissors", color: "#f472b6", progress: 70, lines: [{ label: "Clips generados 10/15", done: true }, { label: "Edición vertical 7/15", done: true }, { label: "Subtítulos 7/15", done: true }, { label: "Programación 5/15", done: false }], footerNote: "En progreso", footerAction: "Ver clips" },
    { id: "a4", index: 4, title: "Reels Instagram", icon: "Camera", color: "#ef4444", progress: 60, lines: [{ label: "Guiones 6/10", done: true }, { label: "Edición 4/10", done: true }, { label: "Diseño portada 4/10", done: false }, { label: "Programación 3/15", done: false }], footerNote: "En progreso", footerAction: "Ver reels" },
    { id: "a5", index: 5, title: "Carrusel", icon: "Rows3", color: "#3b82f6", progress: 100, lines: [{ label: "Diseño", done: true }, { label: "Copywriting", done: true }, { label: "Revisión", done: true }, { label: "Publicado", done: true }], footerNote: "Publicado: 20 mar 2027", footerAction: "Ver carrusel" },
    { id: "a6", index: 6, title: "Artículo SEO", icon: "FileText", color: "#22c55e", progress: 80, lines: [{ label: "Investigación keywords", done: true }, { label: "Outline", done: true }, { label: "Redacción", done: true }, { label: "Optimización SEO", done: true }, { label: "Publicado", done: false }], footerNote: "En revisión final", footerAction: "Ver borrador" },
    { id: "a7", index: 7, title: "PDF / Guía", icon: "FileDown", color: "#a78bfa", progress: 60, lines: [{ label: "Diseño", done: true }, { label: "Contenido", done: true }, { label: "Revisión", done: false }, { label: "Aprobación", done: false }], footerNote: "En diseño", footerAction: "Ver borrador" },
    { id: "a8", index: 8, title: "Email (Secuencia)", icon: "Mail", color: "#22c55e", progress: 30, lines: [{ label: "Estrategia", done: true }, { label: "Redacción emails", done: false }, { label: "Diseño", done: false }, { label: "Programación", done: false }], footerNote: "Inicia: 22 mar 2027", footerAction: "Ver detalle" },
    { id: "a9", index: 9, title: "Academia (Clase)", icon: "GraduationCap", color: "#3b82f6", progress: 20, lines: [{ label: "Guion de la clase", done: true }, { label: "Presentación", done: false }, { label: "Grabación", done: false }, { label: "Publicación", done: false }], footerNote: "Inicia: 25 mar 2027", footerAction: "Ver detalle" },
    { id: "a10", index: 10, title: "Biblioteca", icon: "Library", color: "#94a3b8", progress: 0, lines: [{ label: "Organizar archivos", done: false }, { label: "Etiquetas", done: false }, { label: "Descripción", done: false }, { label: "Archivo final", done: false }], footerNote: "Pendiente", footerAction: "Ver biblioteca" },
  ],
  timeline: [
    { id: "t1", label: "Planeación del episodio", status: "Completado", tone: "emerald", date: "01 mar 2027", done: true },
    { id: "t2", label: "Confirmación de invitada", status: "Completado", tone: "emerald", date: "05 mar 2027", done: true },
    { id: "t3", label: "Guion y preguntas", status: "En Revisión", tone: "amber", date: "08 mar 2027" },
    { id: "t4", label: "Grabación", status: "Programado", tone: "blue", date: "15 mar 2027" },
    { id: "t5", label: "Edición y postproducción", status: "En Producción", tone: "amber", date: "16 – 20 mar 2027" },
    { id: "t6", label: "Publicación Podcast", status: "Programado", tone: "blue", date: "22 mar 2027" },
    { id: "t7", label: "Distribución a plataformas", status: "Programado", tone: "blue", date: "22 – 24 mar 2027" },
  ],
  nextSteps: [
    { id: "n1", label: "Finalizar edición del podcast", done: false, meta: "15 mar" },
    { id: "n2", label: "Grabar clips para Reels y Shorts", done: false, meta: "16 mar" },
    { id: "n3", label: "Crear outline del artículo SEO", done: false, meta: "16 mar" },
    { id: "n4", label: "Diseñar carrusel para Instagram", done: false, meta: "17 mar" },
    { id: "n5", label: "Preparar guía descargable (PDF)", done: false, meta: "18 mar" },
  ],
  productionChecklist: [
    { id: "p1", label: "Guion y preguntas", done: true, meta: "15 feb" },
    { id: "p2", label: "Confirmación de invitada", done: true, meta: "01 mar" },
    { id: "p3", label: "Investigación y notas", done: true, meta: "05 mar" },
    { id: "p4", label: "Grabación", done: true, meta: "15 mar" },
    { id: "p5", label: "Edición de audio/video", done: false, meta: "En progreso" },
    { id: "p6", label: "Revisión final", done: false, meta: "Pendiente" },
    { id: "p7", label: "Aprobación", done: false, meta: "Pendiente" },
    { id: "p8", label: "Publicación", done: false, meta: "Pendiente" },
  ],
  documentsChecklist: [
    { id: "d1", label: "Guion del episodio", done: true },
    { id: "d2", label: "Investigación y estadísticas", done: true },
    { id: "d3", label: "Preguntas para la invitada", done: true },
    { id: "d4", label: "Recursos y referencias", done: true },
    { id: "d5", label: "Descargos legales revisados", done: true },
    { id: "d6", label: "Aprobación de guion", done: false },
    { id: "d7", label: "Material visual / presentación", done: false },
    { id: "d8", label: "Checklist final de publicación", done: false },
    { id: "d9", label: "Permisos y autorizaciones", done: false },
  ],
  resources: [
    { id: "r1", name: "Guion_Ep12_v1.docx", kind: "doc", meta: "DOCX · 48 KB", tag: "Guion" },
    { id: "r2", name: "Investigacion_Trusts.pdf", kind: "pdf", meta: "PDF · 1.2 MB", tag: "Investigación" },
    { id: "r3", name: "Checklist_Trusts.docx", kind: "doc", meta: "DOCX · 38 KB", tag: "Recurso" },
    { id: "r4", name: "Plantilla_Trust_Basico.docx", kind: "doc", meta: "DOCX · 52 KB", tag: "Recurso" },
    { id: "r5", name: "Presentacion_Slides.pdf", kind: "pdf", meta: "PDF · 2.4 MB", tag: "Recurso" },
  ],
  episodeResources: [
    { id: "er1", name: "Brief del episodio.pdf", kind: "pdf", meta: "PDF · 245 KB" },
    { id: "er2", name: "Guion_Ep12_v1.docx", kind: "doc", meta: "DOCX · 48 KB" },
    { id: "er3", name: "Research_Trusts.docx", kind: "doc", meta: "DOCX · 92 KB" },
    { id: "er4", name: "Plan de promoción.pdf", kind: "pdf", meta: "PDF · 320 KB" },
  ],
  documents: [
    { id: "doc1", name: "Guion_Ep12_v1.docx", kind: "doc", meta: "Diana Bermeo · 05 mar 2027", tag: "Guion" },
    { id: "doc2", name: "Investigacion_Trusts.xlsx", kind: "sheet", meta: "Anthony Aguilar · 05 mar 2027", tag: "Investigación" },
    { id: "doc3", name: "Estadisticas_Probate_FL.pdf", kind: "pdf", meta: "Carla Rodríguez · 06 mar 2027", tag: "Referencia" },
    { id: "doc4", name: "Presentacion_Visuales.pptx", kind: "image", meta: "Luis Hernández · 06 mar 2027", tag: "Recurso" },
    { id: "doc5", name: "Checklist_Trusts.docx", kind: "doc", meta: "Diana Bermeo · 07 mar 2027", tag: "Recurso" },
    { id: "doc6", name: "Ejemplos_Casos_Reales.pdf", kind: "pdf", meta: "Sonia M. Gallagher · 08 mar 2027", tag: "Referencia" },
    { id: "doc7", name: "Notas_Invitada.docx", kind: "doc", meta: "Diana Bermeo · 10 mar 2027", tag: "Notas" },
    { id: "doc8", name: "Recursos_Adicionales", kind: "folder", meta: "Anthony Aguilar · 10 mar 2027", tag: "Carpeta" },
  ],
  quickNotes: [
    { id: "q1", icon: "Pin", title: "Enfoque principal", text: "Explicar en lenguaje simple qué es un Trust y por qué sí es para familias promedio.", meta: "10 mar 2027 · Diana Bermeo" },
    { id: "q2", icon: "Flag", title: "Ejemplo clave a incluir", text: "Caso de familia latina en Miami que evitó probate y protegió a sus hijos.", meta: "11 mar 2027 · Anthony Aguilar" },
    { id: "q3", icon: "Lightbulb", title: "Idea para CTA", text: "Ofrecer evaluación gratuita de plan patrimonial + guía descargable.", meta: "12 mar 2027 · Diana Bermeo" },
  ],
  episodeNotes: [
    "Explicar qué es un Trust en lenguaje simple.",
    "Comparar Trust vs Testamento.",
    "Hablar de probate: tiempo, costo y estrés.",
    "Mostrar casos reales (anonimizados).",
    "Incluir opciones para menores y familias mixtas.",
    "Finalizar con próximos pasos concretos.",
  ],
  seoKeywords: ["Trusts", "Living Trust", "Planificación Patrimonial", "Protección de Activos", "Probate", "Sucesión", "Familia Hispana", "Estado de Florida"],
  conversationNotes:
    "<h3>Resumen de la conversación</h3><p>Discutimos por qué los Trusts no son solo para personas ricas, cómo funcionan, qué tipos existen y cómo pueden proteger a la familia, evitar el probate y asegurar que los menores y activos estén bien protegidos.</p><h3>Puntos destacados</h3><ul><li>Los Trusts son más accesibles de lo que la mayoría cree.</li><li>Diferencia entre Testamento vs. Trust.</li><li>Beneficios de evitar probate en Florida.</li><li>Protección de activos y privacidad.</li><li>Casos reales y ejemplos prácticos para familias latinas.</li></ul>",
};
