/** Selección curada de íconos premium para bloques y páginas personalizadas. */
export const ICON_CHOICES = [
  "Layers",
  "Briefcase",
  "Target",
  "Rocket",
  "TrendingUp",
  "Building2",
  "Globe",
  "Users",
  "ShieldCheck",
  "Handshake",
  "Award",
  "Compass",
  "Lightbulb",
  "Gem",
  "Crown",
  "Puzzle",
  "Boxes",
  "ClipboardList",
  "FileText",
  "BarChart3",
  "PieChart",
  "Wallet",
  "CreditCard",
  "Truck",
  "Factory",
  "Store",
  "Megaphone",
  "Mic",
  "Camera",
  "Palette",
] as const;
